experimentName: BrainVasculature_HPT
searchSpaceFile: search_space.json
trialCommand: python run.py --target example_main_BRAVE.py --enable_nni --dataset BrainVasculature_Framingham
trialCodeDirectory: /home/kaiyu/research/git_repos/BrainGB/examples/
trialGpuNumber: 4
trialConcurrency: 16
maxExperimentDuration: 24h
maxTrialNumber: 9000
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
  gpuIndices: [0,1,2,3]
